#!/usr/bin/env bash

# linux-gnu
# darwin12


if [[ "$OSTYPE" = "linux-gnu" ]]; then
  echo "LINUX"
  /etc/init.d/solr stop
  /etc/init.d/solr start
else
  echo "OSX"
  DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  # echo $DIR
  cd $DIR/example
  # pwd
  java -jar start.jar
fi



